### ISSUE TITLE
Login appears to fail

### ISSUE THREAD

**Issue by speedtrap9x** [jasondilworth56/iracingdataapi#39]
No error is reported on completing the init call to connect but I get an error message on the first attempt to retrieve data.
My code has been working for over a year but just started failing around 10/15/2024
When I first saw this, I updated to client 1.2.2 but continue to get the error.
```
  File "...\AppData\Local\Programs\Python\Python312\Lib\site-packages\iracingdataapi\client.py", line 63, in _login
RuntimeError: ('Error from iRacing: ', {'authcode': 0, 'inactive': False, 'message': '**Legacy authorization refused**.', 'verificationRequired': False})
```
call that fails:
a=idc.season_list(the_season_year, the_season_quarter)

full traceback
```
Traceback (most recent call last):
  File "d:\userdata\Terry\Documents\Programming\Python\Cloud-Drive_millerte@hotmail.com\iRacing Py Projs\Season Reader\iRsdav2b.py", line 134, in get_season_series_ids
    a=idc.season_list(the_season_year, the_season_quarter)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Terry\AppData\Local\Programs\Python\Python312\Lib\site-packages\iracingdataapi\client.py", line 1299, in season_list
    return self._get_resource("/data/season/list", payload=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Terry\AppData\Local\Programs\Python\Python312\Lib\site-packages\iracingdataapi\client.py", line 105, in _get_resource
    resource_obj, is_link = self._get_resource_or_link(request_url, payload=payload)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Terry\AppData\Local\Programs\Python\Python312\Lib\site-packages\iracingdataapi\client.py", line 72, in _get_resource_or_link
    self._login()
  File "C:\Users\Terry\AppData\Local\Programs\Python\Python312\Lib\site-packages\iracingdataapi\client.py", line 63, in _login
    raise RuntimeError("Error from iRacing: ", response_data)
RuntimeError: ('Error from iRacing: ', {'authcode': 0, 'inactive': False, 'message': 'Legacy authorization refused.', 'verificationRequired': False})
```

**Comment by abelsm2** [comment]
This is working as intended by iRacing and is not an issue with this library.  Please see the last post on page 5 of this [forum thread](https://forums.iracing.com/discussion/22109/login-form-changes/p5) for information on how to resolve this issue.

**Comment by jasondilworth56** [comment]
Thanks @abelsm2, and yes @speedtrap9x unfortunately this is an iRacing update issue. For what it's worth I fell into the same trap as I'd dared to leave my desk on Wednesday! The good news is it's a very quick fix once you've seen that forum thread.

**Comment by speedtrap9x** [comment]
@abelsm2 and @jasondilworth56 thank you both for your quick replies! Awesome!😁 Greatly appreciated
